-- Fix the DI_weekly_limits_id_seq sequence issue
-- This script will drop the old sequence and let the table recreate it properly

-- First, check if the table exists and what its structure is
DO $$ 
DECLARE
    seq_exists boolean;
    table_exists boolean;
BEGIN
    -- Check if sequence exists
    SELECT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = 'DI_weekly_limits_id_seq'
    ) INTO seq_exists;
    
    -- Check if table exists
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'DI_weekly_limits'
    ) INTO table_exists;
    
    RAISE NOTICE 'Sequence exists: %', seq_exists;
    RAISE NOTICE 'Table exists: %', table_exists;
    
    -- If sequence exists, drop it
    IF seq_exists THEN
        -- First, remove the dependency if the table exists
        IF table_exists THEN
            -- Remove default value that references the sequence
            ALTER TABLE "DI_weekly_limits" ALTER COLUMN "id" DROP DEFAULT;
        END IF;
        
        -- Now drop the sequence
        DROP SEQUENCE IF EXISTS "DI_weekly_limits_id_seq";
        RAISE NOTICE 'Dropped sequence DI_weekly_limits_id_seq';
    END IF;
    
    -- If table exists, recreate the id column with IDENTITY
    IF table_exists THEN
        -- Recreate the column with GENERATED BY DEFAULT AS IDENTITY
        -- This will automatically create the sequence
        ALTER TABLE "DI_weekly_limits" 
        ALTER COLUMN "id" DROP DEFAULT;
        
        ALTER TABLE "DI_weekly_limits" 
        ALTER COLUMN "id" 
        ADD GENERATED BY DEFAULT AS IDENTITY;
        
        RAISE NOTICE 'Recreated id column with IDENTITY';
    END IF;
END $$;
