CREATE TABLE "DI_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "DI_group_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "DI_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "DI_sale" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_sale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"seedsSold" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "DI_sale" ADD CONSTRAINT "DI_sale_groupId_DI_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."DI_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "group_name_idx" ON "DI_group" USING btree ("name");--> statement-breakpoint
CREATE INDEX "name_idx" ON "DI_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "sale_group_idx" ON "DI_sale" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "sale_created_at_idx" ON "DI_sale" USING btree ("createdAt");