CREATE TABLE "DI_leaf_purchase" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_leaf_purchase_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"leavesPurchased" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "DI_leaf_purchase" ADD CONSTRAINT "DI_leaf_purchase_groupId_DI_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."DI_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "leaf_purchase_group_idx" ON "DI_leaf_purchase" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "leaf_purchase_created_at_idx" ON "DI_leaf_purchase" USING btree ("createdAt");