CREATE TABLE "DI_seed_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_seed_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(500),
	"defaultPricePerSeed" integer DEFAULT 700,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "DI_seed_type_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE INDEX "seed_type_name_idx" ON "DI_seed_type" USING btree ("name");
--> statement-breakpoint
-- Insert default seed types
INSERT INTO "DI_seed_type" ("name", "description", "defaultPricePerSeed") VALUES 
  ('Cannabis', 'Cannabis seeds', 700),
  ('Coca', 'Coca seeds', 700);
--> statement-breakpoint
-- Add seedTypeId column with a default value (Cannabis)
ALTER TABLE "DI_sale" ADD COLUMN "seedTypeId" integer DEFAULT 1;
--> statement-breakpoint
ALTER TABLE "DI_internal_seed_sale" ADD COLUMN "seedTypeId" integer DEFAULT 1;
--> statement-breakpoint
-- Update existing records to have Cannabis as seed type
UPDATE "DI_sale" SET "seedTypeId" = 1 WHERE "seedTypeId" IS NULL;
--> statement-breakpoint
UPDATE "DI_internal_seed_sale" SET "seedTypeId" = 1 WHERE "seedTypeId" IS NULL;
--> statement-breakpoint
-- Now make the column NOT NULL
ALTER TABLE "DI_sale" ALTER COLUMN "seedTypeId" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "DI_internal_seed_sale" ALTER COLUMN "seedTypeId" SET NOT NULL;
--> statement-breakpoint
-- Add foreign key constraints
ALTER TABLE "DI_sale" ADD CONSTRAINT "DI_sale_seedTypeId_DI_seed_type_id_fk" FOREIGN KEY ("seedTypeId") REFERENCES "public"."DI_seed_type"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "DI_internal_seed_sale" ADD CONSTRAINT "DI_internal_seed_sale_seedTypeId_DI_seed_type_id_fk" FOREIGN KEY ("seedTypeId") REFERENCES "public"."DI_seed_type"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
-- Create indexes
CREATE INDEX "sale_seed_type_idx" ON "DI_sale" USING btree ("seedTypeId");
--> statement-breakpoint
CREATE INDEX "internal_seed_sale_seed_type_idx" ON "DI_internal_seed_sale" USING btree ("seedTypeId");