CREATE TABLE "DI_leaf_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_leaf_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(500),
	"seedTypeId" integer NOT NULL,
	"defaultPricePerLeaf" integer DEFAULT 200,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "DI_leaf_type_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "DI_leaf_type" ADD CONSTRAINT "DI_leaf_type_seedTypeId_DI_seed_type_id_fk" FOREIGN KEY ("seedTypeId") REFERENCES "public"."DI_seed_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "leaf_type_name_idx" ON "DI_leaf_type" USING btree ("name");--> statement-breakpoint
CREATE INDEX "leaf_type_seed_type_idx" ON "DI_leaf_type" USING btree ("seedTypeId");--> statement-breakpoint
-- Insert default leaf types (Marijuana from Cannabis, Cocaine from Coca)
INSERT INTO "DI_leaf_type" ("name", "description", "seedTypeId", "defaultPricePerLeaf") 
VALUES 
  ('Marijuana', 'Leaf product from Cannabis seeds', 1, 200),
  ('Cocaine', 'Leaf product from Coca seeds', 2, 200);
--> statement-breakpoint
-- Add leafTypeId column with default value to existing tables
ALTER TABLE "DI_internal_leaf_purchase" ADD COLUMN "leafTypeId" integer DEFAULT 1;--> statement-breakpoint
ALTER TABLE "DI_leaf_purchase" ADD COLUMN "leafTypeId" integer DEFAULT 1;--> statement-breakpoint
-- Update existing records to use Marijuana (id=1) as default
UPDATE "DI_internal_leaf_purchase" SET "leafTypeId" = 1 WHERE "leafTypeId" IS NULL;--> statement-breakpoint
UPDATE "DI_leaf_purchase" SET "leafTypeId" = 1 WHERE "leafTypeId" IS NULL;--> statement-breakpoint
-- Remove default and set NOT NULL constraint
ALTER TABLE "DI_internal_leaf_purchase" ALTER COLUMN "leafTypeId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "DI_internal_leaf_purchase" ALTER COLUMN "leafTypeId" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "DI_leaf_purchase" ALTER COLUMN "leafTypeId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "DI_leaf_purchase" ALTER COLUMN "leafTypeId" DROP DEFAULT;--> statement-breakpoint
-- Add foreign key constraints
ALTER TABLE "DI_internal_leaf_purchase" ADD CONSTRAINT "DI_internal_leaf_purchase_leafTypeId_DI_leaf_type_id_fk" FOREIGN KEY ("leafTypeId") REFERENCES "public"."DI_leaf_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "DI_leaf_purchase" ADD CONSTRAINT "DI_leaf_purchase_leafTypeId_DI_leaf_type_id_fk" FOREIGN KEY ("leafTypeId") REFERENCES "public"."DI_leaf_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Create indexes
CREATE INDEX "internal_leaf_purchase_leaf_type_idx" ON "DI_internal_leaf_purchase" USING btree ("leafTypeId");--> statement-breakpoint
CREATE INDEX "leaf_purchase_leaf_type_idx" ON "DI_leaf_purchase" USING btree ("leafTypeId");