CREATE TABLE "DI_group_price" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_group_price_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"itemType" varchar(20) NOT NULL,
	"itemId" integer NOT NULL,
	"price" integer NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "DI_internal_price" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DI_internal_price_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"itemType" varchar(20) NOT NULL,
	"itemId" integer NOT NULL,
	"roleType" varchar(20) NOT NULL,
	"role" varchar(20),
	"price" integer NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "DI_seed_type" ALTER COLUMN "defaultPricePerSeed" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "DI_group_price" ADD CONSTRAINT "DI_group_price_groupId_DI_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."DI_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "group_price_group_idx" ON "DI_group_price" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "group_price_item_idx" ON "DI_group_price" USING btree ("itemType","itemId");--> statement-breakpoint
CREATE UNIQUE INDEX "group_price_unique" ON "DI_group_price" USING btree ("groupId","itemType","itemId");--> statement-breakpoint
CREATE INDEX "internal_price_item_idx" ON "DI_internal_price" USING btree ("itemType","itemId");--> statement-breakpoint
CREATE INDEX "internal_price_role_idx" ON "DI_internal_price" USING btree ("roleType","role");--> statement-breakpoint
CREATE UNIQUE INDEX "internal_price_unique" ON "DI_internal_price" USING btree ("itemType","itemId","roleType","role");